# Generated by Django 6.1 on 2026-08-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_admin_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
