import type { Config } from 'tailwindcss'

// LuxeInvite design system tokens, ported verbatim from
// .docs/specs/app/theme.md (originally app/lib/theme/*.dart in the Flutter
// client, now flutter/lib/theme/*.dart). Do not reinterpret values here —
// this file is a 1:1 translation of that spec's Section 4.
export default {
  content: [],
  theme: {
    extend: {
      colors: {
        luxe: {
          surface: '#FAF9F7',
          'surface-dim': '#DADAD8',
          'surface-bright': '#FAF9F7',
          'surface-container-lowest': '#FFFFFF',
          'surface-container-low': '#F4F3F1',
          'surface-container': '#EFEEEC',
          'surface-container-high': '#E9E8E6',
          'surface-container-highest': '#E3E2E0',
          'on-surface': '#1A1C1B',
          'on-surface-variant': '#3F4942',
          'inverse-surface': '#2F3130',
          'on-inverse-surface': '#F1F1EF',
          outline: '#6F7A72',
          'outline-variant': '#BEC9C0',
          'surface-tint': '#156B49',
          primary: '#00492E',
          'on-primary': '#FFFFFF',
          'primary-container': '#046341',
          'on-primary-container': '#8DDCB1',
          'inverse-primary': '#87D7AC',
          secondary: '#735C00',
          'on-secondary': '#FFFFFF',
          'secondary-container': '#FED65B',
          'on-secondary-container': '#745C00',
          tertiary: '#414121',
          'on-tertiary': '#FFFFFF',
          'tertiary-container': '#585836',
          'on-tertiary-container': '#CFCEA4',
          error: '#BA1A1A',
          'on-error': '#FFFFFF',
          'error-container': '#FFDAD6',
          'on-error-container': '#93000A',
          'primary-fixed': '#A3F4C7',
          'primary-fixed-dim': '#87D7AC',
          'on-primary-fixed': '#002113',
          'on-primary-fixed-variant': '#005235',
          'secondary-fixed': '#FFE088',
          'secondary-fixed-dim': '#E9C349',
          'on-secondary-fixed': '#241A00',
          'on-secondary-fixed-variant': '#574500',
          'tertiary-fixed': '#E6E5B9',
          'tertiary-fixed-dim': '#CAC99F',
          'on-tertiary-fixed': '#1D1D03',
          'on-tertiary-fixed-variant': '#484828',
        },
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'serif'],
        sans: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.36px', fontWeight: '700' }],
        'display-md': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'display-sm': ['34px', { lineHeight: '42px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'title-sm': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.7px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.36px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '2px',
        md: '4px',
        lg: '6px',
        xl: '8px',
        xxl: '12px',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-luxe': '1200px',
      },
    },
  },
} satisfies Config
