# Generated by Django 6.1 on 2026-08-15 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('baptism', 'Baptism')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=64)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('allow_plus_one', models.BooleanField(default=False)),
                ('rsvp_deadline', models.DateTimeField(blank=True, null=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('primary_color', models.CharField(blank=True, max_length=32)),
                ('secondary_color', models.CharField(blank=True, max_length=32)),
                ('font_family', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
